### ISSUE TITLE
Large DEMO transaction counter

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#10]
Add larger DEMO transaction counter for trade shows (click on number and larger pop-out number appears – partly written)

**Comment by sm-shaw** [comment]
Feature has been implemented in v4.7 https://github.com/TPC-Council/HammerDB/pull/494 and described here: https://www.hammerdb.com/blog/uncategorized/hammerdb-v4-7-new-features-pt1-transaction-counter-and-cpu-metrics/
