### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by webysther** [TPC-Council/HammerDB#107]
Created docker with some drivers configured.

https://github.com/webysther/hammerdb-docker

How I make a PR to put this to the project?

**Comment by sm-shaw** [comment]
Also discussed at TPC-OSS Subcommittee meeting 11th May 2021 with Issues #237 and #38 for external Linux packaging. 
Currently, HammerDB is packaged in installer/zip packages for Linux and Windows as both formats support both operating systems for ease of maintenance. 
As with packaging for Linux distributions in .deb and .rpm Docker packaging is also welcome for an external maintainer to manage.
