### ISSUE TITLE
[Question]Failed to run workload with postgre

### ISSUE THREAD

**Issue by ayiyaliing** [TPC-Council/HammerDB#116]
When I run hammerdb against postgre db , the error logs like below, Is there some reason why the function can't be found? Thanks

Vuser 6:FINISHED FAILED
Vuser 7:Processing 100000000 transactions with output suppressed...
Vuser 8:Processing 100000000 transactions with output suppressed...
Vuser 9:Processing 100000000 transactions with output suppressed...
Error in Virtual User 8: ERROR:  function payment(integer, integer, integer, integer, integer, integer, integer, unknown, unknown, integer) does not exist
LINE 1: select payment(1,9,3,2,874,0,723,'','0',0)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

Vuser 8:FINISHED FAILED
Error in Virtual User 7: ERROR:  function payment(integer, integer, integer, integer, integer, integer, integer, unknown, unknown, integer) does not exist
LINE 1: select payment(3,2,2,6,2815,1,1307,'ESEPRIPRES','0',0)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

Vuser 7:FINISHED FAILED
Vuser 10:Processing 100000000 transactions with output suppressed...
Vuser 11:Processing 100000000 transactions with output suppressed...
Error in Virtual User 11: ERROR:  function neword(integer, integer, integer, integer, integer, integer) does not exist
LINE 1: select neword(1,3,3,1380,12,0)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

Vuser 11:FINISHED FAILED
Error in Virtual User 10: ERROR:  function payment(integer, integer, integer, integer, integer, integer, integer, unknown, unknown, integer) does not exist
LINE 1: select payment(3,7,2,6,2507,1,3001,'ESEANTIATION','0',0)
               ^

**Comment by sm-shaw** [comment]
Firstly make sure that the schema build finished correctly.  if this is the case then be aware that there is an option to use stored procedures instead of functions, if you created stored procedures and then run the driver script with functions then you would also see the error above so also try setting PostgreSQL Stored procedures in the driver script to see if you have created stored procedures instead.

**Comment by ayiyaliing** [comment]
Thanks, it solved, I still have a question, when the test run is finished if I can generate a report as xml format or not?

**Comment by sm-shaw** [comment]
If you run hammerdb as a web service all of the functions that run underneath are identical to the GUI and CLI however it stores the output in JSON format in a SQLite database that can be extracted later. The JSON format could be converted to XML if desired. More information is here https://www.hammerdb.com/blog/uncategorized/using-hammerdb-as-a-web-service/.  Although not a feature at present or an Issue for future development it would be possible to add the SQLite based store to the GUI and CLI.

**Comment by ayiyaliing** [comment]
Thanks , Is there a way how can I use the sqlite database? or How can I access the db to extracted the json file.

**Comment by sm-shaw** [comment]
Currently the sqlite database is only accessible when using the web service interface. The documentation for this feature is here  https://www.hammerdb.com/docs/ch09.html and the specific part on retrieving output here https://www.hammerdb.com/docs/ch09s05.html.

**Comment by sm-shaw** [comment]
closed as no further update
