### ISSUE TITLE
Oracle 12.2 multitenant

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#13]
Oracle 12.2 introduced new view AWR_PDB_SNAPSHOT that broke TPM reporting and reports value as 0. HammerDB queries CDB wide DBA_HIST_SNAPSHOT. v$sysstat is now PDB specific. Requires enhancement to detect working in pluggable environment.

**Comment by ek1220** [comment]
When AWR is available (Enterprise Edition) this can be fixed easily: let system user connect to the CDB:
set systemconnect system/manager@mycdb ;# Oracle connect string for system user
set connect tpcc/tpcc@mypdbservice ;# Oracle connect string for tpc-c user
hammerdb would need to differentiate between CDB and PDB/service
you get AWRs and checkpoints by using that setting.

Would be nice if hammerdb CLI could be enhanced with the CDB-name and servicename

**Comment by sm-shaw** [comment]
Thanks for the update, yes that is correct as with #155 connecting as system to the CDB is a workaround to show the TPM correctly and also do the checkpoint.  Yes as with  #14 #15 there are a number of features that could be enhanced to work correctly with CDB/PDB without work arounds. For example also as an alternative using AWR_PDB_SNAPSHOT would also work. This would be an ideal task for someone particularly interested in Oracle pluggable databases to contribute.

**Comment by sm-shaw** [comment]
This is fixed as per #189 and Oracle Doc ID Doc ID 2711623.1DBA_HIST_SYSSTAT is Different Output at CDB and PDB Level from Oracle 18.1 onwards. For Oracle 12 it will continue to be necessary to connect system to the CDB.
