### ISSUE TITLE
Inclusive language updates

### ISSUE THREAD

**Issue by sm-shaw** [TPC-Council/HammerDB#152]
Change master/slave terminology in the remote modes options (functionality to control multiple hammerdb instances instances from a single instance) to primary/replica.  Change prior to v4.0 enables updating code then documentation in a single iteration.

**Comment by elfordINTC** [comment]
Theres a big push for this type of change everywhere these days.

In addition to hammerDB ingredient naming, eventually we'll likely also want to change master branch to main branch.  Github is going to be making a tool to simplify that for pre-existing projects by YE20.  https://github.com/github/renaming
