### ISSUE TITLE
Add Database login reconnect feature

### ISSUE THREAD

**Issue by sm-shaw** [TPC-Council/HammerDB#153]
Currently if a virtual user loses a connection during a test then an error is reported and the connection is lost. For failover/recovery scenarios it would be useful to have a feature where if a connection is lost the error is caught and then the virtual user will attempt to go back to the connection routine and reconnect for a user specified period of time. Once reconnected the workload would continue. This will enable the measurement of how long a database outage took to return to full performance.

**Comment by sm-shaw** [comment]
This feature is already supported. To enable virtual users to reattempt login after failure the following can be done. Set the raiseerror parameter to true so that it would catch the database failure error. Set the iterations value for the virtual user to a high value leave the repeat delay at 500ms.  For SQL Server add “catch {odbc close}” to the top of the driver script – if it errors it won’t call the odbc close at the bottom of the script. This enables the running virtual users to loop trying to reconnect incrementing the iterations value each time. If the database goes away and comes back it does reconnect and then recontinues. 
Note that if the database goes away the monitor virtual user will also lose its connection as well as transaction values and timings so will error trying to capture the timings.
Therefore current functionality should be sufficient for testing the ability of virtual users to reconnect without measuring performance.

**Comment by marjus45** [comment]
Hi @sm-shaw , I wanted to ask a bit more about this. I would indeed like to test failover/recovery scenarios. The database I use is PostgreSQL. From the above I understand that:
1. I should set the Virtual User `iterations` field a large number, e.g.
    ```
    vuset('iterations', 100)
    ```
1. Set the `RAISEERROR` parameter, e.g.
    ```
    diset('tpcc', 'pg_raiseerror', 'true')
    ```
1. Verify that Repeat Delay is set at 500ms
    ```
    print('vuconf')
    ```

From the above I also get that I should change the Driver Script. I presume that is the `loadscript()`s output. What is the command I should put on top of that script in order to achieve re-connection for the Virtual Users for the PostgreSQL?

**Comment by sm-shaw** [comment]
Yes, the iterations value is how many times a Virtual User will run the script it is given, so if the database has failed it will then login again if the database has restarted or report a failed connection if it hasn't. 
In checking the user and repeat delays are reversed from what is documented so there will be a PR to fix this. Therefore for now if you increase the user delay this will introduce a pause between retries to reconnect. 
The GUI gives a better illustration of how this works.
![usedelay](https://github.com/TPC-Council/HammerDB/assets/38044085/e7a3f669-8a75-40b5-aacd-16a025cd25fb)
Nevertheless it should be clear that where the goal is benchmarking testing reconnections where the database fails is not the primary purpose and you will not be able to report accurate performance data.
