### ISSUE TITLE
Hammerdb failed to update Statistics on AWS RDS sql server

### ISSUE THREAD

**Issue by raymond13513** [TPC-Council/HammerDB#159]
For sql server on aws-rds, sp_updatestats fails due to permission error. Here is an article discussing this issue. https://yatb.mitza.net/2017/03/running-spupdatestats-on-aws-rds.html

The error message looks like this when I run tpch or tpcc on aws-rds
```
Vuser 1:UPDATING SCHEMA STATISTICS

Error in Virtual User 1: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]User does not have permission to perform this action.
(executing the statement)

Vuser 1:FINISHED FAILED

ALL VIRTUAL USERS COMPLETE
```

**Comment by sm-shaw** [comment]
Many thanks this looks fine and should not impact the default behaviour while improving on AWS so will be merged and included in the next release.
