### ISSUE TITLE
Postgres benchmark does not works on Azure

### ISSUE THREAD

**Issue by raymond13513** [TPC-Council/HammerDB#163]
Azure are not able to run hammerdb as it throws syntax error similar due to super user having @ in the 
This is due to quirk that Azure have for postgres. Here is another third party tool that Azure broke with some detailed discussion (https://github.com/chef/chef-server/issues/1559). The gist of it is that to login with Azure you need 
    1. Turn on SSL mode 
    2. Uses username@machine_name suffix to login, but after login, any operations related to user name should not have @machine_name suffix

**Comment by sm-shaw** [comment]
Many thanks for the Issue.  We will take a look as this is quite specific to a particular Azure access method so we will need to ensure that it continues to work for PostgreSQL in all cloud and non-cloud environments.

**Comment by raymond13513** [comment]
Thanks a lot for looking into it. I could replicate the change on the other benchmark in the postgres folder if this is the right approach. 

I'm currently developing for PerfKitBenchmarker (https://github.com/GoogleCloudPlatform/PerfKitBenchmarker), a tool that allows user to run benchmarks on multiple cloud with ease. We aim to support Hammerdb in the near future.  It would be great if we could help to test Hammerdb across cloud.

**Comment by sm-shaw** [comment]
Yes someone is looking into it. It appears that the approach is different for newer instances so it is important to get a consistent approach that works for all environments and yes any solution would need to work for the OLTP and OLAP workloads.  The changes won't make it into the next release due soon but we will aim for the best solution for the next dot release. HammerDB is used widely across many clouds already so it should not be too difficult to get the changes to work across them.

**Comment by raymond13513** [comment]
I created a PR https://github.com/TPC-Council/HammerDB/pull/166 on both OLTP and OLAP. I have issues running with OLAP because the missing index makes TPCH runs forever.

**Comment by sm-shaw** [comment]
closed as issue tracked closed PR #166
