### ISSUE TITLE
Postgres TPCH are missing Indexes

### ISSUE THREAD

**Issue by raymond13513** [TPC-Council/HammerDB#164]
The Postgres TPCH benchmark are timing out after the first three queries. 
After a bit digging, I found that Indexes are not created when running Postgres TPCH. 

Here is another article in Japanese that talk about this issue.
https://atsuizo.hatenadiary.jp/entry/2019/09/04/090000

After adding indexes to the tables. The TPCH benchmark becomes comparable to other database engine.
CREATE INDEX ON customer (C_NATIONKEY);
CREATE INDEX ON lineitem (L_ORDERKEY);
CREATE INDEX ON lineitem (L_SUPPKEY);
CREATE INDEX ON lineitem (L_PARTKEY,L_SUPPKEY);
CREATE INDEX ON nation (N_REGIONKEY);
CREATE INDEX ON orders (O_CUSTKEY);
CREATE INDEX ON partsupp (PS_PARTKEY);
CREATE INDEX ON partsupp (PS_SUPPKEY);
CREATE INDEX ON supplier (S_NATIONKEY);
CREATE INDEX ON lineitem (L_SHIPDATE);
CREATE INDEX ON lineitem (L_COMMITDATE);
CREATE INDEX ON lineitem (L_RECEIPTDATE);
CREATE INDEX ON orders (O_ORDERDATE);

**Comment by sm-shaw** [comment]
Many thanks for the Issue. From a quick check and comparison with Oracle the same indexes are created so it is not the case that Indexes are not created at all.  However it may be the case that additional indexes could benefit performance so we will take a look into this as any changes needs to work for multiple schema sizes and also work with the refresh function. 

PostgreSQL
```
schemaname | tablename |  indexname  | tablespace |                                         indexdef                                          
------------+-----------+-------------+------------+-------------------------------------------------------------------------------------------
 public     | region    | region_pk   |            | CREATE UNIQUE INDEX region_pk ON public.region USING btree (r_regionkey)
 public     | nation    | nation_pk   |            | CREATE UNIQUE INDEX nation_pk ON public.nation USING btree (n_nationkey)
 public     | supplier  | supplier_pk |            | CREATE UNIQUE INDEX supplier_pk ON public.supplier USING btree (s_suppkey)
 public     | partsupp  | partsupp_pk |            | CREATE UNIQUE INDEX partsupp_pk ON public.partsupp USING btree (ps_partkey, ps_suppkey)
 public     | part      | part_pk     |            | CREATE UNIQUE INDEX part_pk ON public.part USING btree (p_partkey)
 public     | orders    | orders_pk   |            | CREATE UNIQUE INDEX orders_pk ON public.orders USING btree (o_orderkey)
 public     | lineitem  | lineitem_pk |            | CREATE UNIQUE INDEX lineitem_pk ON public.lineitem USING btree (l_linenumber, l_orderkey)
 public     | customer  | customer_pk |            | CREATE UNIQUE INDEX customer_pk ON public.customer USING btree (c_custkey)
(8 rows)
```
Oracle
```
TABLE_NAME INDEX_NAME	   COLUMN_NAME
---------- --------------- --------------------
CUSTOMER   CUSTOMER_PK	   C_CUSTKEY
LINEITEM   LINEITEM_PK	   L_LINENUMBER
LINEITEM   LINEITEM_PK	   L_ORDERKEY
NATION	   NATION_PK	   N_NATIONKEY
ORDERS	   ORDERS_PK	   O_ORDERKEY
PART	   PART_PK	   P_PARTKEY
PARTSUPP   PARTSUPP_PK	   PS_PARTKEY
PARTSUPP   PARTSUPP_PK	   PS_SUPPKEY
REGION	   REGION_PK	   R_REGIONKEY
SUPPLIER   SUPPLIER_PK	   S_SUPPKEY

10 rows selected.
```

**Comment by sm-shaw** [comment]
So checking the TPC-H specification http://www.tpc.org/tpc_documents_current_versions/pdf/tpc-h_v2.17.1.pdf from which the original workload was written section 1.4.2 Constraints defines what is permissible ie "The  use  of constraints  is  optional  and  limited  to primary  key, foreign  key,  check,  and  not  null  constraints." Section 1.4.2.2 defines the primary keys which we have and 1.4.2.3 defines the foreign key constraints which we also have. Therefore your additional indexes are not permitted if we are to stay within the rules and the current definitions do.

However having said that, if we create indexes on the foreign keys this gives us the performance we need.  Let me see if this is permissible (from 1.4.2 it appears so) and if so I will create a pull request to add these indexes.

```
CREATE INDEX LINEITEM_PART_SUPP_FKIDX ON LINEITEM (L_PARTKEY,L_SUPPKEY);
CREATE INDEX ORDER_CUSTOMER_FKIDX ON ORDERS (O_CUSTKEY);
CREATE INDEX PARTSUPP_PART_FKIDX ON PARTSUPP (PS_PARTKEY);
CREATE INDEX PARTSUPP_SUPPLIER_FKIDX ON PARTSUPP (PS_SUPPKEY);
CREATE INDEX SUPPLIER_NATION_FKIDX ON SUPPLIER (S_NATIONKEY);
CREATE INDEX CUSTOMER_NATION_FKIDX ON CUSTOMER (C_NATIONKEY);
CREATE INDEX NATION_REGIONKEY_FKIDX ON NATION (N_REGIONKEY);
CREATE INDEX IDX_LINEITEM_ORDERKEY_FKIDX ON LINEITEM (L_ORDERKEY);
```

No other indexes would be allowed.
