### ISSUE TITLE
Add limit clause to query10 for TPC-H Oracle

### ISSUE THREAD

**Issue by sravanigomatam** [TPC-Council/HammerDB#172]
The rownum <= 20 clause is missing in Query10 for TPC-H Oracle. Because of this, the run takes longer to complete.

**Comment by sm-shaw** [comment]
Yes you are correct. Checking against the current queries SQL Server for example has the TOP clause to limit the rows but this is missing from Oracle so it returns more data than it should. 

**Oracle**
set sql(10) "select c_custkey, c_name, sum(l_extendedprice * (1 - l_discount)) as revenue, c_acctbal, n_name, c_address, c_phone, c_comment from customer, orders, lineitem, nation where c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate >= date ':1' and o_orderdate < date ':1' + interval '3' month and l_returnflag = 'R' and c_nationkey = n_nationkey group by c_custkey, c_name, c_acctbal, c_phone, n_name, c_address, c_comment order by revenue desc"

**SQL Server**
set sql(10) "select top 20 c_custkey, c_name, sum(l_extendedprice * (1 - l_discount)) as revenue, c_acctbal, n_name, c_address, c_phone, c_comment from customer, orders, lineitem, nation where c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate >= ':1' and o_orderdate < dateadd(mm,3,cast(':1'as datetime)) and l_returnflag = 'R' and c_nationkey = n_nationkey group by c_custkey, c_name, c_acctbal, c_phone, n_name, c_address, c_comment order by revenue desc option (maxdop $maxdop)"

Also checking an official example http://tpc.org/results/fdr/tpch/sun_fire_e25k_10tb_112905_fdr.pdf it is limited as below:
select  *  from  (selectc_custkey,c_name,sum(l_extendedprice * (1 - l_discount)) as revenue,c_acctbal,n_name,c_address,c_phone,c_commentfromcustomer,orders,lineitem,nationwherec_custkey = o_custkeyand l_orderkey = o_orderkeyand o_orderdate >= to_date ('1993-10-01',  'YYYY-MM-DD')and o_orderdate < add_months(  to_date( '1993-10-01','YYYY-MM-DD'),  3)and l_returnflag = 'R'and c_nationkey = n_nationkeygroup byc_custkey,c_name,c_acctbal,c_phone,n_name,c_address,c_commentorder byrevenue desc) where rownum <= 20

or from  12c onwards it could use "FETCH NEXT 20 ROWS ONLY" without the subquery. 
If you would like to submit a pull request for these changes they would be planned for inclusion in the 4.1 release.

**Comment by sm-shaw** [comment]
Same Issue and potential fix applies to Queries 2,3 and 21 making 4 queries in total that need limit adding.
