### ISSUE TITLE
DB2 z/OS support - multi-row insert

### ISSUE THREAD

**Issue by memmertoIBM** [TPC-Council/HammerDB#174]
DB2 on z/OS does not support standard SQL syntax for multi-row insert.
This causes problems with the initial load.

Syntax: INSERT INTO table VALUES ((tuple1), (row2), (row3), ..., (rowN)) FOR n ROWS

https://www.ibm.com/support/knowledgecenter/SSEPEK_12.0.0/sqlref/src/tpc/db2z_sql_insert.html

**Comment by sm-shaw** [comment]
@memmertoIBM this issue is currently self-assigned to you. 
As discussed at TPC-OSS meeting on 14th Nov we have decided to close existing stale issues. 
If this issue is not likely to receive a PR please close as stale.

**Comment by sm-shaw** [comment]
Closed as stale.
