### ISSUE TITLE
DB2 z/OS support - lack of OLD TABLE and NEW TABLE support

### ISSUE THREAD

**Issue by memmertoIBM** [TPC-Council/HammerDB#175]
The TPC-C implementation makes use of OLD TABLE and NEW TABLE support.
DB2 z/OS only supports FINAL TABLE (which is the same as NEW TABLE) and does not support OLD TABLE at all.

Investigate how to rewrite queries given the lack of OLD TABLE support.
Change NEW TABLE to FINAL TABLE, which is equivalent in the absence of triggers or RI constraints.

**Comment by danluksetich** [comment]
Db2 for z/OS does indeed support OLD TABLE in a data-change-table-reference. It is NEW TABLE that is not supported.

**Comment by sm-shaw** [comment]
@memmertoIBM this issue is currently self-assigned to you.
As discussed at TPC-OSS meeting on 14th Nov we have decided to close existing stale issues.
If this issue is not likely to receive a PR please close as stale.

**Comment by sm-shaw** [comment]
Closed as stale.
