### ISSUE TITLE
Invoking customscript with invalid file name fails with error

### ISSUE THREAD

**Issue by dfhawthorne** [TPC-Council/HammerDB#184]
**Overview**
When I invoke the `customscript` command in HammerDB 4.0 with an invalid file name, I get an error.

**To Reproduce**
I ran the following HammerDB CLI command:
```
HammerDB CLI v4.0
Copyright (C) 2003-2020 Steve Shaw
Type "help" for a list of commands
The xml is well-formed, applying configuration
hammerdb>customscript fred
Usage: customscript scriptname.tcl
can't read "_ED(file)": no such element in array
    while executing
"if {$_ED(file) == ""} {return}"
    (procedure "customscript" line 8)
    invoked from within
"customscript fred"
hammerdb>
```

**Expected Output**
The expected output should be:
```
hammerdb>customscript fred
Usage: customscript scriptname.tcl
hammerdb>
```

**Comment by dfhawthorne** [comment]
Pull request #185 created.

**Comment by sm-shaw** [comment]
Many thanks for the Issue and Pull Request, perfect. Yes confirm that it prints the error message and doesn't then return when it should meaning it tries to load a file that doesn't exist, hence the error. The pull request fixes the error by adding the return in the correct place.
