### ISSUE TITLE
GUI HD display

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#19]
Screen shows very small on High Definition Display. Can Use [ winfo screenheight . ] and [ winfo screenwdith .] to determine if screen is HD. Buttons - Create new matching iconsets at 2X the existing iconset size. Use treeview rowheight as per forum thread to increase treeview scale. Check checkboxes (solution online) , spinboxes, dialog sizes. Increase Display 2X.  

(Request by Microsoft 2017)

**Comment by sm-shaw** [comment]
Further information on Tk source code here https://core.tcl-lang.org/tk/tktview?name=1fba28d328 Issue is specifically with 4K UHD displays and will need testing on this type of display

**Comment by sm-shaw** [comment]
Further information is here https://wiki.tcl-lang.org/page/User+Interface+Design%3A+Sizing+of+Elements. It will not be possible to work on adapting HammerDB to a 4K UHD without having a 4K UHD display available to develop and test on.  This Issue will not be worked on for the present time due to the availability of the test hardware. It will be updated when this hardware becomes available.

**Comment by sm-shaw** [comment]
New release of awthemes https://twitter.com/TclLang/status/1252093245313581056?s=20 based on tksvg https://wiki.tcl-lang.org/page/tksvg could provide a more practical and future proof approach to this than the approach above.  Of the current list of themes available https://wiki.tcl-lang.org/page/List+of+ttk+Themes HammerDB uses the clearlooks theme on Linux and xpnative on Windows.  By using tksvg https://github.com/auriocus/tksvg and generating images in SVG format with a scalable theme https://sourceforge.net/projects/tcl-awthemes/ it should be possible to create a single version of HammerDB to scale up to UHD displays.

**Comment by sm-shaw** [comment]
The approach described previously has been successful.  By adding the tksvg and awthemes packages, converting all images to SVG format and rewriting the code to move from fixed to scalable dimensions HammerDB v4.0 will include scalable graphics as per the example shown on Microsoft Surface laptop.  The pull request will be linked to this Issue.
![snip1](https://user-images.githubusercontent.com/38044085/93482325-7f070b00-f8f7-11ea-8a57-a60e9471037d.PNG)
