### ISSUE TITLE
HammerDB Load Testing

### ISSUE THREAD

**Issue by nhariba2** [TPC-Council/HammerDB#195]
I have installed HammerDB on windows PC 8GB Ram/i5 Dualcore.
Trying to performance benchmarking comparison between on-prem sql server Vs SQL Server on Azure Arc (on-prem)
Any test we perform , CPU on my PC (where HameerDB is installed) is shooting to 100%.
So unable to collect the metrics we need.
Note: Connection to target system is getting established, databases\transactions are getting generated on the target servers, but not able to collect those metrics on my PC (where HammerDB is installed)

Any advise ?

**Comment by sm-shaw** [comment]
Hi, the issue is not entirely clear but it sounds like you are testing a database on your local machine instead?  The best place to start is with the quick start guide  https://www.hammerdb.com/docs/ch02.html so the steps are, 1. build a schema, 2, run a test workload to make sure it is working, 3. run a timed workload, 4 check the transaction counter. Make sure the connection information is for the remote system and not the local one. The workload runs with stored procedures so all of the load in on the database.

**Comment by nhariba2** [comment]
I have installed HammerDB on windows PC 8GB Ram/i5 Dualcore.
Trying to performance benchmarking comparison between on-prem sql server Vs SQL Server on Azure Arc (on-prem)
Any test we perform , CPU on my PC (where HameerDB is installed) is shooting to 100%.
So unable to collect the metrics we need.
Note: Connection to target system is getting established, databases\transactions are getting generated on the target servers, but not able to collect those metrics on my PC (where HammerDB is installed)

Any advise ?

**Comment by sm-shaw** [comment]
Great, so how many Virtual Users have you created, does it still do it with 1 VU?  Also make sure that you have set the option "Exit on SQL Server Error" - if sessions are spinning without running transactions or having them error then this will cause the CPU to spike on the client.  Also check task manager/resource monitor to see where the CPU is going and confirm it is in HammerDB. Have you run the test workload with output with a small number of virtual users to make sure it is running correctly. Also check the network configuration ODBC in particular can use more bandwidth.

**Comment by nhariba2** [comment]
Am trying to build the schema in hammerdb but its taking time to creating rows on tables its keeps on generating nearly 1lakhs records.  May i know how to reduce number of records creation, due to that am unable to proceed on hammerdb.  Its taking more than 5hrs also still records keep on generating. May i know the values of virtual users and warehouse, etc to be entered? Those values should be complete schema build process quickly, here am help less.  I have given varies values virtual user and warehouse still same issues taking more time to complete schema build.   I have entered 1wareshouse and one virtual user for 8gb ram and 2core sql machine keeps on generating the rows on tables...
