### ISSUE TITLE
Build schema

### ISSUE THREAD

**Issue by nhariba2** [TPC-Council/HammerDB#201]
Am trying to build the schema in hammerdb but its taking time to creating rows on tables its keeps on generating nearly 1lakhs records. May i know how to reduce number of records creation, due to this issue am unable to proceed on hammerdb. Its taking more than 5hrs also still records keep on generating. May i know the values of virtual users and warehouse, etc to be entered? Here am help less. I have given varies values virtual user and warehouse still same issues taking more time to complete schema build. I have entered 1wareshouse and one virtual user for 8gb ram and 2core sql machine keeps on generating the rows in tables... Also let me know how many records will be generate on default while build schema on each tables?

**Comment by sm-shaw** [comment]
Hi you have the same question here  #199 this is not an Issue and has been converted to a discussion topic. Please read the advice on #199 and follow up on Discussions and not Issues. This Issue will be closed.

**Comment by sm-shaw** [comment]
closed as not an Issue, topic is covered in #199
