### ISSUE TITLE
CREATE OR ALTER PROCEDURE appears only SQL Server 2016 SP1

### ISSUE THREAD

**Issue by i25652** [TPC-Council/HammerDB#246]
Hi
I just downloaded HammerDb 4.1  and it fails to create schema on SQL Server because Update Statistic part contains 
"CREATE OR ALTER PROCEDURE" which appears only on SQL Server 2016 SP1
I can override this, but it can be confusing for many.

**Comment by sm-shaw** [comment]
Hi
This was introduced in v4.0 related to this issue https://github.com/TPC-Council/HammerDB/issues/159 where statistics could not be updated when running on AWS RDS.  To use the previous way on older versions of SQL Server you can select the Azure checkbox (even if not running on Azure) pre-create the database and then run the build.  This will then just execute "EXEC sp_updatestats" instead.
