### ISSUE TITLE
[TPROC-H] MySQL create FKs after table load.

### ISSUE THREAD

**Issue by lrweck** [TPC-Council/HammerDB#264]
Creating the FKs beforehand makes loading large amounts of data unnecessarily slow, as it could (and should) be created afterwards, like it does on PostgreSQL.

**Comment by sm-shaw** [comment]
Can you provide more information on your test environment, in particular the storage engine you are using. Although the foreign keys are included in the table definitions, the default storage engine is MyISAM and when this was checked most recently queries on MyISAM were still faster than InnoDB.  Also, have you tried the system variable foreign_key_checks, setting this to 0 should allow the foreign keys to be created but not checked during the build.

**Comment by lrweck** [comment]
Hi! I'm using InnoDB.

My objective was to create similar environments for testing both MySQL and PostgreSQL. I know loading data is not supposed to be used to be a benchmark, but since the code is similar and we're talking about the same data being loaded, it could reasonably be something measured. I believe simply disabling foreign_key_checks still incurs a penalty for each INSERT, so it's not really the same as creating the index from scratch.

So I'd like to propose having the same loading methods for at least PostgreSQL and MySQL (and MariaDB, since it's basically MySQL)

**Comment by sm-shaw** [comment]
Have you tried setting foreign_key_checks to 0 at a system level? 
The simplest solution to account for different storage engines would be to set foreign_key_checks to 0 within the build script, this would be straightforward. 
I would recommend some caution about expecting exactly the same performance from MariaDB and MySQL they have diverged somewhat and therefore this shouldn't necessarily be assumed depending on the versions you are testing.

**Comment by lrweck** [comment]
I haven't tried setting it... However, FK checking is just part of the question. Even if they are disabled, each insert still has to update their respective indices.

**Comment by sm-shaw** [comment]
Thanks, when time permits we'll benchmark a number of options to evaluate the best approach.

**Comment by lrweck** [comment]
Actually, HammerDB already sets "foreign_key_checks = 0"... 
![image](https://user-images.githubusercontent.com/26086198/127578003-14515c26-3b0f-48db-9d2f-a97bfc708ade.png)

**Comment by sm-shaw** [comment]
Good catch.  If you wish to submit a pull request to create the indexes and foreign keys after the build and can show the performance improvement for different storage engines then that would be a good approach.  Otherwise this will be added to the list of development task.

**Comment by lrweck** [comment]
@sm-shaw I'll see if I can publish it on the weekend. Tcl is extremely new to me. In fact, I've never laid a finger on it before having to use HammerDB

**Comment by sm-shaw** [comment]
Tcl is used as the HammerDB glue language for its multi-threaded parallelism (languages such as Python are restricted by the GIL meaning you can only run one thread at a time) more information is here:
https://www.hammerdb.com/blog/uncategorized/what-programming-languages-does-hammerdb-use-and-why-does-it-matter/
https://www.youtube.com/watch?v=PAktFHBT_QU&t=8s
Tcl is really easy to learn - this book is very comprehensive https://www.magicsplat.com/ttpl/index.html but the wiki here is a great reference.
The source for the build script you want to edit is in `/src/mysql/mysqlolap.tcl` - this is loaded in the GUI (or CLI) when you do a build. 
The structure for what you want to do is already in the scripts so you don't need to wrtie any new Tcl. It is only a case of creating a new proc for CreateIndexes and moving the index and foreign key creation after the data load. 
So you would add a proc such as the following below. Remove the index and foreign keys from the table creation and put them in this proc and then call this proc just before CreateIndexes. 
Hopefully it should be seen that you don't actually need much/any Tcl knowledge at all - it is getting the SQL right to break out the table and index/foreign key creation that is key. 

```
CreateIndexes $mysql_handler
GatherStatistics $mysql_handler
```
This is set to 2 SQL statements - just change the for loop $i <= 2 to the number of statements needed. 
```
proc CreateIndexes { mysql_handler } {
puts "CREATING INDEXES"
set sql(1) "INDEX/FK CREATION GOES HERE"
set sql(2) "INDEX/FK CREATION GOES HERE"
for { set i 1 } { $i <= 2 } { incr i } {
mysqlexec $mysql_handler $sql($i)
                }
return
}
```
Steve
