### ISSUE TITLE
virtual users cannot connect using SSL/TLS certificates with MariaDB instance running in SkySQL on AWS

### ISSUE THREAD

**Issue by ckolovson** [TPC-Council/HammerDB#267]
I am getting the following error: 
Error in Virtual User 1: mariaconnect/db server: Access denied for user 'xxx-user'@'yyy-hostname' (using password: YES). 
The output from Virtual User 1 shows:
Vuser 1:CREATING TPCC SCHEMA
Vuser 1:the tcp connection to 'yyy-hostname':'zzz-port' could not be established

It appears that the virtual users cannot authenticate when SSL/TLS certificates are required.

UPDATE: I found a workaround by creating a SkySQL service with SSL/TLS disabled. Is it possible for virtual users to authenticate  using SSL/TLS certificates?

**Comment by sm-shaw** [comment]
By default, in the build and driver scripts there is a "proc" called ConnecttoMaria - this calls the command "mariaconnect" and passes the options given to HammerDB such as using sockets or host/port username and password.

mariaconnect -host $host -port $port -user $user -password $password

However mariaconnect does support more options including ssl and therefore to enable this you can modify the scripts directly to add the following options: 

-ssl boolean
    Switch to SSL after handshake. Default is false 
-sslkey string
    is the pathname to the key file. Used if -ssl is true 
-sslcert string
    is the pathname to the certificate file. Used if -ssl is true 
-sslca string
    is the pathname to the certificate authority file. Used if -ssl is true 
-sslcapath string
    is the pathname to a directory that contains trusted SSL CA certificates in pem format. Used if -ssl is true 
-sslcipher string
    is a list of allowable ciphers to use for SSL encryption. Used if -ssl is true 

HammerDB also supports using TLS directly eg https://www.hammerdb.com/docs/ch15s01.html

**Comment by ckolovson** [comment]
Thanks!!

**Comment by sm-shaw** [comment]
Just to note that this pull request https://github.com/TPC-Council/HammerDB/pull/331 adds SSL/TLS support for MariaDB and has been tested against SkySQL
