### ISSUE TITLE
Error in Virtual User 1: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]关键字 'OR' 附近有语法错误。 [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'CREATE/ALTER PROCEDURE' 必须是查询批次中的第一个语句。

### ISSUE THREAD

**Issue by dpm112233** [TPC-Council/HammerDB#275]
hammerDB test sql server2012 perfomance,schema build respond Error in Virtual User 1: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]关键字 'OR' 附近有语法错误。
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'CREATE/ALTER PROCEDURE' 必须是查询批次中的第一个语句。
(executing the statement)

**Comment by sm-shaw** [comment]
Closed as no further update
