### ISSUE TITLE
Check available disk space before start build warehouses

### ISSUE THREAD

**Issue by codyyf** [TPC-Council/HammerDB#343]
Hi Steve

I'm using HammerDB to benchmark MariaDB, is it possible for the tool to check the available disk space before start to build the schema/warehouses.  Or Give user an estimated requires disk spaces for the # of warehouses they want to build.  For example, I'm creating 1000 warehouses on my server and after wait 3-4 hours it failed because lack of disk space....So I have to either add another SSD or maybe create less warehouses and try again, thanks.

Thanks,
Cody

**Comment by sm-shaw** [comment]
There is some TPROC-C sizing guidance here https://www.hammerdb.com/blog/uncategorized/hammerdb-v4-2-new-features-pt2-increase-of-tproc-c-schema-size-limits/

This is a reasonable suggestion, but not something that would take priority at the present time. Therefore, as open source best practice this would be a great opportunity to make a code contribution to add a feature important to you. 

What you would need to do is fork HammerDB and add a feature that checks the available disk space. This would need to be done for all 6 databases for both Windows and Linux for both TPROC-C & H - so you would need to verify the sizing guidance is accurate for 24 separate builds. Then please make a pull request, we can review it and if working correctly your feature will be added. Please advise if you plan to work on this and then the issue can remain open.
