### ISSUE TITLE
Add “dropschema” function for GUI, CLI & Webservice

### ISSUE THREAD

**Issue by Jiang-Hua** [TPC-Council/HammerDB#351]
HammerDB could provide a button/command to drop the database instead of doing it manually, in this way users don’t have to figure out various SQL commands to clean up the environment for different databases.

**Comment by sm-shaw** [comment]
Delete icon in SVG & PNG formats has been added here: https://github.com/TPC-Council/HammerDB/compare/master...sm-shaw:HammerDB:351
