### ISSUE TITLE
RPM for Linux installs

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#38]
Build RPM for Linux installations so automatically loads dependencies (eg Xft fonts)

**Comment by sm-shaw** [comment]
New issue with the graphical installer on Gnome 3 could make an RPM install a more viable alternative to overcome GUI installation issues in Linux. 
Graphical installer freezes on Linux Gnome 3 desktop with meta_window_unminimize: assertion '!window->override_redirect' failed #78

**Comment by memmertoIBM** [comment]
Relevant references:
* https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/rpm_packaging_guide/index

**Comment by sm-shaw** [comment]
Discussed at TPC-OSS Subcommittee meeting 11th May 2021. 
Currently HammerDB is packaged in installer/zip packages for Linux and Windows as both formats support both operating systems for ease of maintenance. 
HammerDB does not install dependencies as a user of one database may not need the libraries for all of the other supported databases. 
Additional packaging for Linux distributions in .deb and .rpm format is welcome but as with ArchLinux requires additional help to do the packaging and maintain in-line with future releases.
Note Issue #237 is a similar Issue for DEBIAN/UBUNTU packaging.

**Comment by sm-shaw** [comment]
As discussed at TPC-OSS meeting 14th Nov.
This issue was transferred from the original HammerDB sourceforge project to the TPC-Council on GitHub and having not been actioned in the interim period is now considered stale.
If there is a wish to contribute this enhancement, then this issue can be reopened and self-assigned.
