### ISSUE TITLE
Update mysqltcl MySQL prepared statements and update 

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#39]
(already in github release of mysqltcl)

**Comment by abondvt89** [comment]
Steve currently looking at this.  Evaluating tdbc::mysql.  Newer interface.

**Comment by sm-shaw** [comment]
Branch of mysqltcl https://github.com/xdobry/mysqltcl/blob/pstatement/generic/mysqltcl.c included prepared statements but was not complete.

Alternative and updated interface is tdbc::mysql however this advises here: 

http://tcl.2662.n7.nabble.com/TDBC-stored-procedures-output-parameters-and-multiple-results-td50670.html  that "MySQL is rather in disarray with respect to the support of stored procedures" and should use something like: 
```
  procedurename(:param1, :param2, :param3)
     where :param1 is an IN VARCHAR, :param2 is an INOUT INTEGER,
     and :param3 is an OUT VARCHAR, would translate to a sequence
     like:
         @param1 = 'escaped string'
         @param2 = numeric-value
         CALL procedurename(@param1, @param2, @param3)
     followed by:
         SELECT @param2, @param3
```
Therefore current best alternative for MySQL prepared statements is to prepare on the server side and call with variables as follows: 
```
mysql evaldirect "prepare slev_st from 'CALL SLEV(?,?,?,@stock_count)'"
mysql evaldirect "set @st_w_id=$w_id,@st_d_id=$stock_level_d_id,@threshold=$threshold"
mysql evaldirect "execute slev_st using @st_w_id,@st_d_id,@threshold"
mysql evaldirect "select @stock_count"
```
Testing will determine whether this offers any performance improvements over the current mysqtcl interface and whether the move to tdbc::mysql is preferred for future releases.

**Comment by sm-shaw** [comment]
tdbc::mysql appears slower than mysqltcl also client side errors on closing threads such as:
`Error in my_thread_global_end(): 2 threads didn't exit`
Will not use tdbc::mysql - evaluating mysqltcl with server side prepared to assess performance.

**Comment by sm-shaw** [comment]
(Comment now in correct issue)
Pull Request 39 MySQL prepared statements added for this feature to be selected by the user. Also added socket connection option for MySQL. Fixed warnings in stored procedures for date formatting using str_to_date and added return value to slev stored procedure. Added Fetch values to driver scripts to ensure consistency with other implementations.

Evaluated tdbc::mysql but not as efficient as current mysqltcl and printed error message to stdout.
Evaluated padding on InnoDB storage engine in similar approach used for SQL Server. Padding as below at TEXT(1000) was found to be the best using innochecksum to verify that rows per page were reduced and improved performance by 1-2% - however modifying the MySQL block size was found to be better at achieving the same result with a less invasive approach and was not implemented.
```

CREATE TABLE `district` (
  `d_id` INT(2) NOT NULL,
  `d_w_id` INT(4) NOT NULL,
  `d_ytd` DECIMAL(12, 2) NULL,
  `d_tax` DECIMAL(4, 4) NULL,
  `d_next_o_id` INT NULL,
  `d_name` VARCHAR(10) BINARY NULL,
  `d_street_1` VARCHAR(20) BINARY NULL,
  `d_street_2` VARCHAR(20) BINARY NULL,
  `d_city` VARCHAR(20) BINARY NULL,
  `d_state` CHAR(2) BINARY NULL,
  `d_zip` CHAR(9) BINARY NULL,
`padding` TEXT(1000) NOT NULL,
PRIMARY KEY (`d_w_id`,`d_id`)
)
alter table district alter padding set default (repeat('X',1000))
```

Revisited expensive select for update in NEWORD

```
SELECT d_next_o_id, d_tax INTO no_d_next_o_id, no_d_tax
FROM district
WHERE d_id = no_d_id AND d_w_id = no_w_id FOR UPDATE;
UPDATE district SET d_next_o_id = d_next_o_id + 1 WHERE d_id = no_d_id AND d_w_id = no_w_id;
```

It continues to remain not possible to implement this in one statement such as the example below from PostgreSQL and has been left unmodified in MySQL
`UPDATE district SET d_next_o_id = d_next_o_id + 1 WHERE d_id = no_d_id AND d_w_id = no_w_id RETURNING d_next_o_id, d_tax INTO no_d_next_o_id, no_d_tax;`

**Comment by sm-shaw** [comment]
Closed per pull request 39 MySQL prepared statements #98
