### ISSUE TITLE
Modified interface - DB2

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#40]
DB2 interface has been modified but source not released or packaged as open source

**Comment by abondvt89** [comment]
Changed in the library.  Source not in github or public.  From a packaging point to view.  Matt will work on getting the changes pushed to the repos for the library.

**Comment by tasdevil13** [comment]
What can be done or can be helped with to bring the new Db2 driver (with parameter markers) to open source?
I'm working currently on a internal test team, who would like to run HammerDB against a Db2 for z/OS system and for loading, we'd probably need to update the driver to support Db2 for z/OS plus the INSERT FOR n ROWS VALUES syntax (see https://www.ibm.com/support/knowledgecenter/SSEPEK_11.0.0/sqlref/src/tpc/db2z_sql_insert.html )

**Comment by memmertoIBM** [comment]
@tasdevil13 I've created new issues #174 and #175 to track these DB2 z/OS issues.
I need to follow up with @abondvt89 and @sm-shaw to understand exactly what bits were missing in the client library.

**Comment by sm-shaw** [comment]
Closing issue as db2tcl source now fully available as used by HammerDB including automated build on Windows #362 and Linux  #323 
Details on running automated build here https://www.hammerdb.com/blog/uncategorized/how-to-build-hammerdb-from-source/
Following this guide gives all source, makefiles etc for building db2tcl as used by HammerDB, nothing now remains in changed library that has not been released.
