### ISSUE TITLE
 Add sqlecrea and sqledrpd APIs to db2tcl used by HammerDB

### ISSUE THREAD

**Issue by sm-shaw** [TPC-Council/HammerDB#431]
Currently, HammerDB asks the user to create the Db2 database manually and the drop schema functionality added in #430 uses OS commands. The db2tcl interface used by HammerDB should add the sqlecrea and sqledrpd APIs so the creation and drop can be done from within HammerDB using the correct commands.

**Comment by Jiang-Hua** [comment]
Added new APIs - db2_create_db, db2_drop_db and db2_force_off to db2tcl based on APIs of libdb2api (sqlecrea, sqledrpd and sqlefrce) . The new APIs will be integrated into the latest HammerDB.
