### ISSUE TITLE
MariaDB schema question

### ISSUE THREAD

**Issue by mariadb-DmitryVolkov** [TPC-Council/HammerDB#435]
TPC_C (https://www.tpc.org/tpc_documents_current_versions/pdf/tpc-c_v5.11.0.pdf) defines Stock table with:  

S_W_ID Foreign Key, references W_ID
S_I_ID Foreign Key, references I_ID

Is that a reasonable assumption that Foreign Key has to be covered by indexes?  Otherwise, once enforced, they will cause a full table scan. 

looking at MariaDB create table I don't see any indexes (except the primary key):
https://github.com/TPC-Council/HammerDB/blob/master/src/mariadb/mariaoltp.tcl#L639-L658

**Comment by sm-shaw** [comment]
It is not a mandatory requirement to have foreign keys and all the full disclosure reports reviewed on tpc.org have not implemented foreign keys are far as I can see. Although we do want to distinguish between the official audited TPC-C from the specification and the derived version TPROC-C in HammerDB, so we can also clearly say for TPROC-C foreign keys are not required. 

Also some MariaDB storage engines do not implement foreign keys such as MyRocks https://mariadb.com/kb/es/foreign-key-support-for-myrocks/,  https://github.com/facebook/mysql-5.6/issues/618.

So the current index implementation should fine for the widest use and you can also look at the other database to see how the indexes are implemented there.

**Comment by mariadb-DmitryVolkov** [comment]
"It is not a mandatory requirement to have foreign keys" - that is a surprise for me. Well, that explains why the derived version TPROC-C is implemented as it is. I am going to close this issue.  Thank you @sm-shaw

**Comment by memmertoIBM** [comment]
I can understand why this would be a surprise.  More modern workloads (such as TPC-E) require the use of full referential integrity.

While foreign keys are listed in the table layouts (clause 1.3), this is for reference only; there is no requirement to implement them.  The integrity rules (clause 1.5) only require that primary keys be implemented to enforce uniqueness.

You are correct, though, that *if* foreign keys were defined and enforced, the appropriate covering indexes would be required to avoid table scans.

**Comment by mariadb-DmitryVolkov** [comment]
"This is for reference only; there is no requirement to implement them." - yeah, I missed that part. Thanks, Matthew.
