### ISSUE TITLE
Publish Docker Image on Release

### ISSUE THREAD

**Issue by dnascimento** [TPC-Council/HammerDB#447]
Could we build and publish a docker image when we release this repo?

**Comment by sm-shaw** [comment]
Yes we do.

The official/supported HammerDB docker image for v4.5 is here https://hub.docker.com/r/tpcorg/hammerdb-v4.5. 

We currently tag all of the releases and from v4.5 we also have a v4.5-docker tag https://github.com/TPC-Council/HammerDB/tree/v4.5-docker corresponding to the v4.5 Docker image. (So once we have the new release the Docker file will be updated along with new scripts etc). Going forward  all releases will have a docket tag that corresponds to the Docker image on Dockerhub. 

These are all under the official TPC account here https://hub.docker.com/u/tpcorg
