### ISSUE TITLE
Consider changing "Benchmark Options" from TPC-C or TPC-H to something that underscores "based on TPC-C/TPC-H"

### ISSUE THREAD

**Issue by elfordINTC** [TPC-Council/HammerDB#46]
The UI, allows choosing benchmark TPC-C or TPC-H.  Because HammerDB is not audited, the workload is based on TPC-C/TPC-H.  

TPC workloads are generally pretty poor at having different terminology to distinguish between the workload mix and the benchmark itself.  XBB is the best in that the workload mix is "BigBench" and the workload is tpcx-bb.

Realistically, TPC may need to come up with a preferred way to refer to the workload mix as separate from the benchmark proper.

![bench](https://user-images.githubusercontent.com/20116871/51920834-ff7f9d80-239a-11e9-87b2-2eb419b7eec9.png)

**Comment by sm-shaw** [comment]
This is not a documentation bug per se. If the terminology is to be changed this needs to decided upon and then done with a pull request and changed in the code first and then the documentation changed to reflect this.  The code is the same for the UI and CLI at this level. Another suggestion put forward is TPC-C-cloud for an alternative.

**Comment by elfordINTC** [comment]
should stay open until compliance is confirmed by TPC fair use policies experts.  If its going to be done via pull request, need to have an owner identified and stay open until completed.  Note that "TPC-C cloud" would imply that there is a workload called "TPC-C cloud" which would itself violate fair use I believe.

**Comment by abondvt89** [comment]
Reopening issue to check against compliance with TPC Fair Use document.

**Comment by memmertoIBM** [comment]
Relevant TPC Policies wording (From Policies v6.14):

**8.1.3 Use of the TPC Benchmark Name and Metrics**

If a party wishes to use the TPC Benchmark name in public material to describe work that is derived from TPC material, the prefix “Derived from” must appear before all instances of the TPC Benchmark name

**8.1.4 TPC Benchmark Disclaimer**

All work derived from TPC Benchmarks must have the following disclaimer: The <name of derived work> is derived from the <TPC Benchmark name> and as such is not comparable to published <TPC Benchmark name> results, as the <name of the derived work> results do not comply with the <TPC Benchmark name>.

**8.3 Fair Use of TPC Specifications**

If TPC Benchmark Standards or parts of TPC specifications are used to develop other non-TPC benchmarks, then:
8.3.1 The Use of TPC Material (Policies § 8.1) and Fair Use Policy (Policies § 8.2.1) must not be violated.
8.3.2 All variations from the TPC specifications in question must be explicitly noted.
8.3.3 Results based on the non-TPC benchmark must be clearly identified as not being comparable to an official TPC Result.

**Comment by memmertoIBM** [comment]
For compliance with 8.1.3, there are two options:
1) "Derived from TPC-C" and/or "Derived from TPC-H", wherever TPC-C and TPC-H are used
2) Come up with a new name, like Hammer-C and Hammer-H, and use it everywhere.

For compliance with 8.1.4, we just need to add the disclaimer.  I would suggest somewhere in the UI as well as the documentation.

For compliance with 8.3:
- clause 8.3.1 is covered by the requirements of 8.1.3 and 8.1.4
- clause 8.3.2 would be covered by a section in the documentation outlining the deviations
- clause 8.3.3 would be covered by the disclaimer (8.1.4), and we'd likely want something in the "report" that is generated.

**Comment by abondvt89** [comment]
Naming change to OS-TPC-C and OS-TPC-H
