### ISSUE TITLE
Update hammerdb docs ch03s02.html

### ISSUE THREAD

**Issue by elfordINTC** [TPC-Council/HammerDB#47]
https://www.hammerdb.com/docs/ch03s02.html - 
[CE] this needs assorted updates…  And a new section probably on auditing and distinguishing OSS workload execution from TPC benchmark publications…

As defined by the TPC "TPC benchmarks are industry standards. The TPC, at no charge, distributes its benchmark specifications to the public." For this reason HammerDB includes an implementation of the specification of the TPC-C benchmark that can be run in supported database environments. Implementing the TPC-C specification has the significant advantage that you know that the test is reliable, scalable and tested to produce accurate, repeatable and consistent results.

The TPC published an additional benchmark specification for transactional systems called TPC-E introduced in February 2007. However unlike TPC-C this benchmark has not been widely adopted by all of the commercial database vendors.

**Comment by sm-shaw** [comment]
Removed last sentence.  If the wording is to be changed then this needs to be a pull request with the desired wording ie "PR should draft the right wording" provided in advanced for the wording to be changed to.

**Comment by elfordINTC** [comment]
should stay open until compliance is confirmed by TPC fair use policies experts.

**Comment by abondvt89** [comment]
Reopening issue to check against compliance with TPC Fair Use document.

**Comment by abondvt89** [comment]
Rewording of 3.2 for TPC-C description and OS-TPC-C description.  Related to issue #51
