### ISSUE TITLE
Install libxft-dev and libcairo2-dev in Docker build to enable GUI support

### ISSUE THREAD

**Issue by sm-shaw** [TPC-Council/HammerDB#497]
Although the GUI is not the primary use case for the Docker image it does work by installing some additional packages and therefore these should be added by default in case running the GUI is desired.

As an example, in the host disable access control.
```
xhost +
access control disabled, clients can connect from any host
```
and then run the docker image and run the hammerdb gui. The command fails on finding libXft (for antialiased text)
```
hammerdb@REDPOLL:~$ sudo docker run --network=host -it --name hammerdb tpcorg/hammerdb bash
root@REDPOLL:/home/hammerdb/HammerDB-4.6# export DISPLAY=:0
root@REDPOLL:/home/hammerdb/HammerDB-4.6# ./hammerdb
wish8.6: error while loading shared libraries: libXft.so.2: cannot open shared object file: No such file or directory
```
This can be resolved by installing libxft-dev in the docker image and therefore should be included in the default build.
Also v4.7 GUI has a dependency on Cairo graphics and this should also be installed by default for future support. (GUI Linux environments tested all install these packages by default). 

```
root@REDPOLL:/home/hammerdb/HammerDB-4.6# apt-get install libxft-dev
root@REDPOLL:/home/hammerdb/HammerDB-4.6# apt-get install libcairo2-dev

example shows hammerdb in docker running GUI on host display.
```
![hdbdocker](https://user-images.githubusercontent.com/38044085/214869408-9668a136-17f3-4e88-b16a-430605683335.PNG)

**Comment by sm-shaw** [comment]
As per #496 we should also add

`apt-get install -y lsb-release`

by default to ensure that the SQL Server ODBC installs work correctly.

**Comment by pooja-jain-17** [comment]
Yes it should work fine. 
however if the host server itself doesn't have GUI, then it would be great to first have Xorg, Xauth etc installed and X11 Forwarding enabled. 

I have tried it and adding following to Dockerfile to build a new image 

`RUN apt install libxft-dev libcairo2-dev xauth`

and starting the container as below, should work. 
```
#docker run -it --rm -v /root/.Xauthority:/root/.Xauthority -e DISPLAY=$DISPLAY --network=host --name hammerdb hammerdb-v4.6 bash
```

**Comment by pooja-jain-17** [comment]
I have updated the Dockerfile to reflect the same. 
 https://github.com/pooja-jain-17/HammerDB/blob/cfa94f7bc30b50a1c374c42964d9fbfab8c8a6cc/Docker/Dockerfile

Will create a pull request once we have all the changes for HammerDB 4.7 included.
