### ISSUE TITLE
Include the sample scripts as part of HammerDB Distribution package

### ISSUE THREAD

**Issue by pooja-jain-17** [TPC-Council/HammerDB#508]
Can we have the [scripts](https://github.com/TPC-Council/HammerDB/tree/master/Docker/scripts) directory placed in the HammerDB main directory and be bundled in HammerDB package. Rather than being part of only Docker image. 

This will accomplish the following objectives:
1.	Anyone using HammerDB, with or without Docker will have access to the scripts. 
2.	Anyone can pickup the HammerDB Dockerfile and build their own image without having to additionally download the scripts folder. Dockerfile will be sufficient, enabling a straightforward deployment. 
3.	This will make it easier to create database specific Dockerfiles as outlined in Issue #[506](https://github.com/TPC-Council/HammerDB/issues/506)

**Comment by sm-shaw** [comment]
This is a very good suggestion and one we should implement to include the example scripts in the main directory.

**Comment by sm-shaw** [comment]
Also, if we are including the sample scripts in the main HammerDB directory, then we should also add a Windows powershell script alongside the current bash shell - this way the scripts will be able to run on Windows also. To keep things more straightforward, I will open a new issue to track this.
