### ISSUE TITLE
update hammerdb docs ch09s01.html

### ISSUE THREAD

**Issue by elfordINTC** [TPC-Council/HammerDB#51]
Similar to issue posted on TPC-E.  This relates to TPC-H part of the docs.

[CE] Similar need to update wording to align to a TPC approach to distinguish workload from benchmark.  In this case for H.

Several places in the text need updates.

**Comment by sm-shaw** [comment]
Section has been modified to remove QphH and replace with geomean advice.

**Comment by elfordINTC** [comment]
should stay open until compliance is confirmed by TPC fair use policies experts.

**Comment by abondvt89** [comment]
Reopening issue to check against compliance with TPC Fair Use document.

**Comment by abondvt89** [comment]
Sections 10.1 and Sections 3.2 need to be updated with descriptions of what is TPC-C/H and what OS-TPC-C/H mean in the context of HammerDB.
