### ISSUE TITLE
doc review needed for ch09s04

### ISSUE THREAD

**Issue by elfordINTC** [TPC-Council/HammerDB#52]
https://www.hammerdb.com/docs/ch09s04.html - “Using RedShift”

[CE] Not sure about needed updates here.  I seem to recall some challenges with redshift not following TPC rules but I may be misremembering.

**Comment by sm-shaw** [comment]
This is in the section "cloud analytic queries" and were queries made freely available by Oracle at Oracle Openworld 2016 - example link to this report was here https://www.business-standard.com/article/news-ians/oracle-beats-amazon-web-services-in-cloud-database-comparison-116092101444_1.html. Therefore this does not need to follow TPC rules.

**Comment by elfordINTC** [comment]
should stay open until compliance is confirmed by TPC fair use policies experts.

**Comment by abondvt89** [comment]
Reopening issue to check against compliance with TPC Fair Use document.

**Comment by abondvt89** [comment]
Section 4.0 will need some minor tweeks around derived from.  Different queries run on a TPC-H schema.
