### ISSUE TITLE
Parameter "password" for ms sql connection is not isolated

### ISSUE THREAD

**Issue by vbienf** [TPC-Council/HammerDB#523]
**Guidance**
Bug reports are for when HammerDB is not behaving as expected.
Bug reports should not be submitted for help in understanding database performance related questions.
General questions on database performance or HammerDB usability should be submitted under Discussions.

**Describe the bug**
I have a test-database with auto-generated admin password: "6IeC13B$l4" When I tried to build TPC-C schema I have an error in log "Error in Virtual User 1: Error: can't read "l4": no such variable" and non-error and empty in GUI-window.

**To Reproduce**
1. Go to MS SQL Server TPROC-C benchmark
2. Click on 'Option'
3. Add database connection and password like "abc$defg", in my case it was "6IeC13B$l4"
4. Click on 'Build'
5. See error

**Expected behavior**
HammerDB shouldn't respond to special characters in passwords

**Screenshots**

![image](https://user-images.githubusercontent.com/3448218/225051061-8073d7cf-7250-49c3-b079-ff8401d6f5e2.png)
![image](https://user-images.githubusercontent.com/3448218/225052798-4f432d7a-0e95-4867-9d8d-d13f2677577e.png)
![image](https://user-images.githubusercontent.com/3448218/225051214-ac0b7094-e835-433c-af8b-d9d038830357.png)

**HammerDB Version (please complete the following information):**
 - Version:  4.6
 - Build: Release download 

**HammerDB Interface (please complete the following information):**
 - UI: GUI 

**Operating System (please complete the following information):**
 - Server OS: RHEL8
 - Client OS: RHEL8

**Database Server (please complete the following information):**
 - Database name: MS SQL Server
 - Database Release Version 2022

**Database Client (please complete the following information):**
 -  ODBC Driver 18 for SQL Server

**Additional context**
-

**Comment by sm-shaw** [comment]
Hi, yes this is known in the passwords so the $ is a special character that identifies a variable. So in this example pa$$word will look to resolve the variable $word
<img width="308" alt="image" src="https://user-images.githubusercontent.com/38044085/225073537-915a529b-969b-4816-ae18-e8568ffd4cdb.png">
as shown here:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/38044085/225073847-6b1e24db-075f-4df9-940f-216f3b79a310.png">
To prevent this happening in more basic examples wrap the password in curly braces {} as shown here: 
<img width="308" alt="image" src="https://user-images.githubusercontent.com/38044085/225074036-ee711632-7203-44ca-8be8-10ca06760615.png">
Then this will not resolve the special characters and pass the password unmodified. 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/38044085/225074200-2dcc31c2-b2ed-40ba-bb34-53b1e72a51a0.png">
A more complex example is shown here https://github.com/TPC-Council/HammerDB/discussions/349
and for more these more complex examples wrap the password with `{[ concat {} ]}` instead.

As these solutions are so straightforward and gives the flexibility of writing code in the fields up to now we have not looked to fix the recognition of special characters.  Similarly as it is a test environment we also do not hide the password fields either. 
Both are valid behaviours to change although to now not many people have pressed for it, once they know the code based solutions. 

Nevertheless a pull request is always welcome if there is a strong desire to change the password (and other fields) recognition of special characters and to hide the passwords in the GUI entry fields.

**Comment by sm-shaw** [comment]
Discussed at TPC-OSS meeting, not a high priority fix as workaround is straightforward.
@vbienf please advise if this works for you and/or interest in adding a fix.

**Comment by sm-shaw** [comment]
Closed as not planned
