### ISSUE TITLE
doc update for ch10s11.html

### ISSUE THREAD

**Issue by elfordINTC** [TPC-Council/HammerDB#53]

**Comment by sm-shaw** [comment]
Section and link removed from documentation in process of updating

**Comment by elfordINTC** [comment]
should stay open until compliance is confirmed by TPC fair use policies experts.

**Comment by abondvt89** [comment]
Reopening issue to check against compliance with TPC Fair Use document.

**Comment by abondvt89** [comment]
Fixed in version 3.3 of the documentation
