### ISSUE TITLE
Add MariaDB as a separate database

### ISSUE THREAD

**Issue by abondvt89** [TPC-Council/HammerDB#54]

**Comment by sm-shaw** [comment]
starting template now in https://github.com/sm-shaw/HammerDB/tree/54

**Comment by Jiang-Hua** [comment]
Added MariaDB as a separate database in https://github.com/Jiang-Hua/HammerDB.git

**Comment by Jiang-Hua** [comment]
An extension to TCL that provides access to MariaDB server.
https://github.com/Jiang-Hua/mariatcl.git

**Comment by sm-shaw** [comment]
This looks great. I will review the code from the current repositories and provide any feedback. There may be some minor changes to update to features in the v4.1 release eg in the opt file there is now the option for logging the transaction counter output, however the changes needed should be minor.

**Comment by sm-shaw** [comment]
I have made pull requests to both the extension and the MariaDB code itself.  
Please check and verify the changes. It now looks good to create a pull request to the main TPC-Council/HammerDB project.

**Comment by sm-shaw** [comment]
Testing done on GUI & CLI with TPROC-C and TPROC-H.  Added additional v4.1 features already in MySQL.
For TPROC-C Use allwarehouse, time profile (v4.1) asynch scale and connect pooling have all been tested and verified to work.
Pull request https://github.com/Jiang-Hua/HammerDB/pull/1 removed some additional indentation formatting as this had offset the scripts in the script editor and also prevented some of the dynamic insertion points working for some of the features above. 
One integrated further testing is recommended however this is now fully working as an interface to MariaDB using mariatcl and the MariaDB provided library without using any mysql software. 
Pull request for mariatcl interface here https://github.com/Jiang-Hua/mariatcl/pull/1

**Comment by sm-shaw** [comment]
Screenshot HammerDB with MariaDB
![mdb](https://user-images.githubusercontent.com/38044085/115108830-654fa400-9f6a-11eb-927d-373a74f4d6ce.png)

**Comment by Jiang-Hua** [comment]
Merged the changes from Shaw and created a pull request to the main TPC-Council/HammerDB project.
