### ISSUE TITLE
have the option to deploy the database in a Db2 purescale cluster by adjusting the database schema.

### ISSUE THREAD

**Issue by guidoverbraak** [TPC-Council/HammerDB#549]
The current database schema for a TPCC database in Db2 has some constructions in it that are not supported in IBM's Db2 pureScale or not desired.
-  range clustered tables, to be recognized by the clause "organize by row using key sequence" in the create table statement
-  some other "alter table" statements like "lock table" or "append on". These ones are not mandatory to remove but lock table is a bit against the grain in a datasharing environment.

If these constructions are removed the schema can be deployed in a pureScale environmentwhich is highly suitable for TPCC tests.

**Comment by memmertoIBM** [comment]
This is a consequence of using Db2's historical TPC-C benchmark schema for HammerDB.

Adding support for a more traditional schema that is compatible with Db2 pureScale (and Db2 z/OS) will need to be championed by IBM.

**Comment by sm-shaw** [comment]
This is something that would need to be submitted by someone with access to a Db2 pureScale environment to be able to test the changes. Also, as noted by @memmertoIBM, we have outstanding Issues for z/OS https://github.com/TPC-Council/HammerDB/issues/174 https://github.com/TPC-Council/HammerDB/issues/175 that would need a z/OS system for testing. 
We would be glad to accept pull requests to introduce these changes. 
A useful template would be what we have done for PostgreSQL with 2 compatible options of "EnterpriseDB Oracle compatible" and "Citus Compatible" (that are mutually exclusive in this case). A similar approach could be added for Db2 for pureScale compatible and z/OS compatible by someone who could do the changes and test that they work.
![image](https://user-images.githubusercontent.com/38044085/234539435-427909c4-00f9-4021-8340-e7787145e6be.png)
