### ISSUE TITLE
include version naming scheme of container images release

### ISSUE THREAD

**Issue by grooverdan** [TPC-Council/HammerDB#570]
**Is your feature request related to a problem? Please describe.**

To use tpcorg/hammerdb:maria is comes as the latest version, but multiple HammerDB versions may exist and for consistency in scripting it would be useful to have this version tagged.

**Describe the solution you'd like**

Looking for instances at the [php](https://github.com/docker-library/docs/blob/master/php/README.md#supported-tags-and-respective-dockerfile-links) tag scheme of the Docker Official Images, a version tag like:

tpcorg/hammerdb:v4.8-maria is a constent naming scheme. Starting with a version tag is useful for those that use tools like renovate to keep up to date.

**Describe alternatives you've considered**

tpcorg/hammerdb:maria-v4.8 - possible, no major downside

tpcorg/hammerdb_mariadb:v4.8 - would involve addition repos, no major downsides

**Additional context**

Would apply to other dbs too.

**Comment by pooja-jain-17** [comment]
Great suggestion. Initially, the idea was to maintain these database specific images only for the latest version of HammerDB. But, we can incorporate this from v4.8 docker release. Thanks.

tpcorg/hammerdb:maria-v4.8

**Comment by sm-shaw** [comment]
This has been included in the v4.8 docker release
