### ISSUE TITLE
Containers - use volume for SQLite database (and logs)

### ISSUE THREAD

**Issue by grooverdan** [TPC-Council/HammerDB#571]
**Is your feature request related to a problem? Please describe.**

Starting a test run begins with:
```
Initialized new SQLite on-disk database /tmp/hammer.DB
```

The tmp directory is of a limited size. As a many use case will want to preserve the test run, the logical place to put is is in its own volume.

**Describe the solution you'd like**

In the base container, an explicit volume will define where the data id stored.
```
VOLUME /data
```

And the necessary environment to use this as a write location (`set tmpdir /data`(?), or `$::env(LOGS)` where `ENV LOGS` is in the containerfile).

(I'm open to other better names than `/data` too).

**Describe alternatives you've considered**

A non-explict volume can be created and start with `--volume volumename:/tmp`, but `/tmp` is used for other things I assume.

**Comment by sm-shaw** [comment]
Great question.

So yes, this is configurable. The base configuration is set in the xml files in the config directory with the jobs SQLite database being set in the commandline section of generic.xml by specifying the filename. So if for example I wanted to change this to hammer.db in in the DATA directory, I would set this as follows:

```
<commandline>
    <sqlite_db>/home/steve/HammerDB-4.8/DATA/hammer.db</sqlite_db> 
       <keepalive_margin>10</keepalive_margin>
       <jobsoutput>JSON</jobsoutput>
       <jobs_disable>0</jobs_disable>
</commandline>
```
Then HammerDB would initialize this file:
```
$ ./hammerdbcli
HammerDB CLI v4.8
Copyright (C) 2003-2023 Steve Shaw
Type "help" for a list of commands
Initialized new Jobs on-disk database /home/steve/HammerDB-4.8/DATA/hammer.db
```
and continue to use it:
```
$ ./hammerdbcli 
HammerDB CLI v4.8
Copyright (C) 2003-2023 Steve Shaw
Type "help" for a list of commands
Initialized Jobs on-disk database /home/steve/HammerDB-4.8/DATA/hammer.db using existing tables (45,056 KB)
```
Note that this is the Jobs SQLite database. We also have the configuration SQLite databases that persists the configuration over restarts.  This also includes the jobs SQLite database location, so after the configuration SQLite databases are created then changes to the XML files are not re-read until the files are deleted (or it detects a different version of HammerDB and will refresh them automatically). The location of the configuration SQLite files are also configurable in generic.xml in the following location. 
```
  <sqlitedb>
        <sqlitedb_dir>TMP</sqlitedb_dir>
   </sqlitedb>
```
So, having said this, the best approach is probably to leave the configuration as TMP and set an environment variable to the preferred location.  On Linux it will look for environment variables TMP, TMPDIR, or TEMP and then finally look for /tmp. 
On Windows it will look for TEMP, TMP, TMPDIR or finally C:\.
Most Windows users will have user temp directory persisted over reboots which tends to work well. 
```
C:\Program Files\HammerDB-4.8>set TEMP
TEMP=C:\Users\Steve\AppData\Local\Temp
```
Going back to Linux as an example, without changing the config, if you set the TMP environment variable to a preferred directory, then it will use this for both the jobs database and the config databases. 
```
$ export TMP=`pwd`/DATA
$ ./hammerdbcli 
HammerDB CLI v4.8
Copyright (C) 2003-2023 Steve Shaw
Type "help" for a list of commands
Initialized new Jobs on-disk database /home/steve/HammerDB-4.8/DATA/hammer.DB
```
So this DATA directory contains the following files. 

```
hammerdb>ls -1 DATA
database.db
db2.db
generic.db
hammer.DB
mariadb.db
mssqlserver.db
mysql.db
oracle.db
postgresql.db
```
It is safe to delete any of these files at any time (obviously it will lose the config or jobs data) as HammerDB will recreate them if missing. Also if you want to change the location the file can be copied manually from one location to another. 

In the example CLI scripts the driving shell script includes the following, so by default creates a TMP directory in the HammerDB home directory for storing the SQLite files and other text based logfiles. 
```
export TMP=`pwd`/TMP
mkdir -p $TMP
```
On Windows we don't set it in the powershell driver script as the default user temp directory tends to be an ideal location.

**Comment by sm-shaw** [comment]
Closing, as this is already configurable. However, can be re-opened if a more specific solution is needed.
