### ISSUE TITLE
Hammerdb 4.4 with Oracle RAC: transcation count in hdbcount logfile reports transactions only for a one instance

### ISSUE THREAD

**Issue by ek1220** [TPC-Council/HammerDB#578]
I'm running hammerdb 4.4 with Oracle RAC 19.
transactions are recorded every minute in hdbtcount-logfile.
When I checked those transaction numbers they show transactions for only one instance
For example:
194460 Oracle tpm @ Mon Jun 26 14:33:23 UTC 2023
189540 Oracle tpm @ Mon Jun 26 14:33:24 UTC 2023
182880 Oracle tpm @ Mon Jun 26 14:33:25 UTC 2023
192540 Oracle tpm @ Mon Jun 26 14:33:26 UTC 2023
196980 Oracle tpm @ Mon Jun 26 14:33:27 UTC 2023
In fact we do twice as many transactions when I compute the numbers from AWRs.

**Comment by sm-shaw** [comment]
Do "print dict", is rac set to 0?

```
Dictionary Settings for Oracle
connection {
 system_user     = system
 system_password = manager
 instance        = oracle
 rac             = 0
}
```
If it is set it to 1
```
hammerdb>diset connection rac 1
Changed connection:rac from 0 to 1 for Oracle
```
Then you should see the global rather than local transactions

**Comment by sm-shaw** [comment]
Closed as resolved as no further update
