### ISSUE TITLE
Add PK to be able to bench group replication in MySQL

### ISSUE THREAD

**Issue by martinwalle** [TPC-Council/HammerDB#580]
https://github.com/TPC-Council/HammerDB/blob/8ad6b64472fa8ee8fc60b51267a50847876b296b/src/mysql/mysqloltp.tcl#L555

Hello,

Could you add these lines to add an invisible PK to the table history ?
  `id` INT NOT NULL AUTO_INCREMENT INVISIBLE,
PRIMARY KEY (`id`)

for the whole table:
```
    set sql(3) "CREATE TABLE `history` (
  `h_c_id` INT NULL,
  `h_c_d_id` INT NULL,
  `h_c_w_id` INT NULL,
  `h_d_id` INT NULL,
  `h_w_id` INT NULL,
  `h_date` DATETIME NULL,
  `h_amount` DECIMAL(6, 2) NULL,
  `h_data` VARCHAR(24) BINARY NULL,
  `id` INT NOT NULL AUTO_INCREMENT INVISIBLE,
PRIMARY KEY (`id`)
)
ENGINE = $mysql_storage_engine"
```

It works for me.

Sincerely,
Martin

**Comment by sm-shaw** [comment]
This seems reasonable, however it would be best to make it an option in case there are versions that do not support the keywords.

**Comment by sm-shaw** [comment]
Pull Request #586 adds this feature as a choosable option.
