### ISSUE TITLE
Extend tdbc::odbc interface to add BCP commands for SQL Server schema builds

### ISSUE THREAD

**Issue by sm-shaw** [TPC-Council/HammerDB#594]
Pull Requests #587 #592 have added bcp based loads for the SQL Server TPROC-C schema, significantly improving build times. Issue #593 proposes the same update for the TPROC-H schema. 

Currently, this feature uses the external bcp command called via exec. It should be possible to extend the tdbc::odbc interface to add the bcp_init, bind and sendrow commands and call these directly from ODBC rather than using the external bcp command

https://learn.microsoft.com/en-us/sql/relational-databases/native-client-odbc-extensions-bulk-copy-functions/bcp-init?view=sql-server-ver16
https://learn.microsoft.com/en-us/sql/relational-databases/native-client-odbc-extensions-bulk-copy-functions/bcp-bind?view=sql-server-ver16
https://learn.microsoft.com/en-us/sql/relational-databases/native-client-odbc-extensions-bulk-copy-functions/bcp-sendrow?view=sql-server-ver16

**Comment by sm-shaw** [comment]
Pull request #653 added. As noted in the PR the long-term solution is to extend the ODBC interface that HammerDB uses to include bcp based commands https://github.com/TPC-Council/HammerDB/issues/594 as using the executable is the cause of issues such as this where the login connection and the bcp connection are out of synch.

**Comment by JoshInnis** [comment]
I have been revisiting this issue, and I have some questions about the details how to approach this.

For extending tdbc::odbc, you mean, pull down the source code and add the bcp options directly into the library? or is it more about using the odbc library that Microsoft developed with this functions in them? Or is there perhaps another route to do this that I have missed?

**Comment by sm-shaw** [comment]
I have had a further look into this and made some additional changes to the tdbc::odbc package to enable it for bcp. Firstly we have to enable for bcp before we connect, and also we need to load an additional library such as msodbcsql17 or msodbcsql18 for the additional functionality (bcp_initA, bcp_exec etc), however I have some concerns about over complexity with having to load the additional libraries. 

So, when you said, _Or is there perhaps another route to do this that I have missed?_ I now think there could be! as, in researching implementing bcp in the library it referenced using bulk insert as a SQL statement instead. This inherits the connection, so we don't need to reconnect to do this. Also, the current bcp implementation doesn't work for entra authentication, however if we inherit the existing connection then I don't see why using bulk insert wouldn't be able to use entra?. 

Doing this, it could use the existing method where we create a flatfile and bulk load it, so would be a very straightforward enhancement and the bcpComm proc would become much simpler like this: (passing just the existing odbc connection instead of uid pwd server to reconnect)
```
proc bcpComm { odbc tableName filepath } {
 $odbc evaldirect [ subst {bulk insert $tableName from "$filepath" with (DATAFILETYPE = 'char', FIELDTERMINATOR = ',',ROWS_PER_BATCH=500000)}]
}
```
this is instead of the more complicated proc we now use here to account for the different connection types and needs extending each time we have another connection option: 
```
# bcp command to copy from file to specified tables
# -b flag specifies batch size of 500000, -a flag specifies network packet size of 16000
# network packet size depends on server configuration, default of 4096 is used if 16000 is not allowed
proc bcpComm { tableName filePath uid pwd server} {
   upvar 3 authentication authentication
   if {[ string toupper $authentication ] eq "WINDOWS" } {
       exec bcp $tableName IN $filePath -b 500000 -a 16000 -T -S $server -c  -t ","
   } else {
   upvar #0 tcl_platform tcl_platform
        if {$tcl_platform(platform) == "windows"} {
#bcp on Windows uses ODBC driver 17 that does not support the -u option and may need updating when bcp driver changes
       exec bcp $tableName IN $filePath -b 500000 -a 16000 -U $uid -P $pwd -S $server -c  -t ","
    } else { 
#bcp on Linux can use ODBC driver 18 and trust the server certificate with -u option
   upvar 3 trust_cert trust_cert
   upvar 3 odbc_driver odbc_driver
   regexp {ODBC\ Driver\ ([0-9]+)\ for\ SQL\ Server} $odbc_driver all odbc_version 
   if { $trust_cert && $odbc_version >= 18 } {
       exec bcp $tableName IN $filePath -b 500000 -a 16000 -U $uid -P $pwd -S $server -u -c  -t ","
        } else {
       exec bcp $tableName IN $filePath -b 500000 -a 16000 -U $uid -P $pwd -S $server -c  -t ","
       }
    }
   }
}
```
Also, we wouldn't be dependent on the external bcp.exe binary, in initial tests, this works, is faster and would be more reliable and forward compatible than extending the tdbc::odbc interface as I originally planned. 

Thoughts, comments appreciated, especially if this would provide a solution to doing schema builds with entra. If so, I will make the change to use bulk insert and do a PR. I was thinking of keeping the description, flags and proc names as use bcp (instead of changing to bulk insert) for compatibility with existing scripts.
