### ISSUE TITLE
HammerDB CLI in container in MSSQLS mode not finding MSSQL ODBC drivers

### ISSUE THREAD

**Issue by zinzh** [TPC-Council/HammerDB#595]
**Description**
Hammerdb CLI in container in MSSQLS mode not finding MSSQL ODBC drivers

**To Reproduce**
1. Run hammerdb container from the provided official image
2. select mssqls mode from hammerdbcli
3. use any parameters to connect to an MSSQL database

**Expected behavior**
Can connect to the DB and build the schema

**Screenshots**
![edited2](https://github.com/TPC-Council/HammerDB/assets/96527865/8b590c0e-0319-4316-ad06-d42e0f79fefc)

**HammerDB Version**
HammerDB v4.8

**HammerDB Interface**
 - CLI

**Operating System (please complete the following information):**
HammerDb CLI in container (base image Ubuntu 20.04)

**Database Server (please complete the following information):**
15.0.4316

**Database Client (please complete the following information):**
 Based on container image

**Additional context**
In MSSQL Dockerfile, msodbcsql18 is being installed without specifying a version, however, in the same Dockerfile the line Driver=/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.1.so.2.1 is being added in /usr/local/unixODBC/etc/odbcinst.ini with a specific version .

Installing msodbcsql18 with specific version 18.1.2.1-1 solves the issue since a newer version has been released from microsoft (18.3.1.1-1)

Replacing `ACCEPT_EULA=Y DEBIAN_FRONTEND=noninteractive apt-get install -y msodbcsql18 && \` with `ACCEPT_EULA=Y DEBIAN_FRONTEND=noninteractive apt-get install -y msodbcsql18==18.1.2.1-1 && \`

**Comment by pooja-jain-17** [comment]
'librarycheck' passes on the both the images from
 1. [Docker Hub](https://hub.docker.com/r/tpcorg/hammerdb/tags) 
`docker pull tpcorg/hammerdb:mssqls`
 2.  And the image built from [Dockerfile](https://github.com/TPC-Council/HammerDB/blob/master/Docker/mssqls/Dockerfile) 

Also the library /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.2.so.2.1 is present in both of these images

 
![image](https://github.com/TPC-Council/HammerDB/assets/99299346/b6d7eab9-ce6d-428a-9f75-9e96192d3846)

**Comment by zinzh** [comment]
@pooja-jain-17 Yes, but the path to the driver in `/usr/local/unixODBC/etc/odbcinst.ini` is still pointing to an older version which is causing the error

**Comment by zinzh** [comment]
I will open a PR with the fix i suggested so that we do not face the issue again when a new version is released from microsoft and gets automatically selected for installation, thanks @pooja-jain-17
