### ISSUE TITLE
Problems with SUM

### ISSUE THREAD

**Issue by HelenBianchi** [TPC-Council/HammerDB#603]
TIBERO - When I did a query with SUM I don't why the result is more than the correct result.

**Comment by sm-shaw** [comment]
HammerDB does not support TIBERO. There is an issue where someone was working on adding support themselves, however this issue https://github.com/TPC-Council/HammerDB/issues/63 has been idle for a long time.
You would need to ask your question on SUM and TIBERO to someone at TIBERO.

**Comment by sm-shaw** [comment]
Closed as TIBERO not currently supported
