### ISSUE TITLE
wrong # args: should be " mssql connection string build is wrong when username/password contains semicoin

### ISSUE THREAD

**Issue by d00lar** [TPC-Council/HammerDB#606]
**Describe the bug**
the bug is 
wrong # args: should be "..... when in user password there is ';'

**To Reproduce**
1. Go to sql server deploy OPTIONS
2. change to sql authentication / enter sql username/password that contains ; in it (usualy in pass) =] 
3. Run workload '....'
4. See error in Virtual User 1: wrong # args: should be "do_tpcc server port odbc_driver authentication uid pwd tcp azure count_ware db imdb bucket_factor durability num_vu"

**Expected behavior**
it should be possible to have ';' in password. probably it need to be in '' when building connectionstring ;)

**HammerDB Version (please complete the following information):**
 - Version: [e.g. 4.7] / 4.0 also

**HammerDB Interface (please complete the following information):**
 - UI: GUI

**Operating System (please complete the following information):**
 - Client OS:any windows

**Database Server (please complete the following information):**
 - i checked onmy mssql cause thats what i wanted to benchmark but probably in all will be the same issue?

**Database Client (please complete the following information):**
 - Database client name: ODBC Driver 18 for SQL Server

**Comment by sm-shaw** [comment]
This is discussed in issue #561 as a workaround wrap the password with special characters with: {} or  {[ concat {} ]}

    simple cases use: {}
    more complex cases use: {[ concat {} ]}
