### ISSUE TITLE
WebService API does not return current db http://127.0.0.1:8080/print?db

### ISSUE THREAD

**Issue by xychar** [TPC-Council/HammerDB#61]
From WebService interface, could not get the current db (set by dbset).

In browser, open "http://127.0.0.1:8080/print?db", will get:
{
  "ora": "Oracle",
  "mssqls": "MSSQLServer",
  "db2": "Db2",
  "mysql": "MySQL",
  "pg": "PostgreSQL",
  "redis": "Redis"
}

**Comment by sm-shaw** [comment]
Fixed in commit a19a8df

**Comment by abondvt89** [comment]
Closing as fixed.
