### ISSUE TITLE
[FEATURE REQUEST] Connection Timeouts Retry to Connect Before Failing

### ISSUE THREAD

**Issue by JoshInnis** [TPC-Council/HammerDB#625]
**Is your feature request related to a problem? Please describe.**
When the number of vusers is set at or above the available number of threads on the workstation, some of the connections will timeout.

**Describe the solution you'd like**
Threads will retry connections a certain number of times before throwing an error to improve the likelihood of a successful load.

**Describe alternatives you've considered**
The alternative is to reduce the number of users to reduce or to rerun the workload from the beginning when the error occurs.

**Additional context**
Example Error Message

Error in Virtual User 9: SQLState = S1T00, NativeError = 0
Error = [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired
SQLState = 08001, NativeError = 258
Error = [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Timeout error [258].
SQLState = 08001, NativeError = 258
Error = [Microsoft][ODBC Driver 17 for SQL Server]Unable to complete login process due to delay in prelogin response
child process exited abnormally
Vuser 9:FINISHED FAILED

**Comment by sm-shaw** [comment]
We can discuss this in the TPC-OSS, however some research in the error shows:

https://learn.microsoft.com/en-us/answers/questions/1195513/getting-timeout-error(258)-unable-to-complete-logi

This error about "delay in prelogin response" often indicates that there is a problem in the connection to the AD if you are on on-prem and you are using Windows Authentication.

So it looks like the prelogin response is an error that is external to the database and would not be something we could fix.

**Comment by sm-shaw** [comment]
Closed as "delay in prelogin response" appears related to Windows authentication.
