### ISSUE TITLE
Suggest to create branches for 2.x & 3.x respectively

### ISSUE THREAD

**Issue by xychar** [TPC-Council/HammerDB#64]
You would like to have cleaner folder for each version. 
Please ignore if you don't feel it is good.

**Comment by sm-shaw** [comment]
This is a good suggestion as when you fork the project currently you get all of the v2 directories and files that are no longer relevant. Someone from the project team will take a look at doing this.

**Comment by abondvt89** [comment]
I think what we may want to do here is create a branch for 2.x and then submit code changes to the master branch to remove what is no longer needed for for 3.x.   So anyone working on 3.x would be able to fork or branch off of master and only get what is needed for the 3.x code.

**Comment by sm-shaw** [comment]
Done as suggested by @abondvt89 - created branch version 2.23 for the final release of v2. Deleted v2 only files and directories in commit 6b64ca0 from master. Fork from master will now only give latest v3.
