### ISSUE TITLE
SQL Server TPROC-C Driver Options screen needs scroll bar so i can configure all options

### ISSUE THREAD

**Issue by richardw1313** [TPC-Council/HammerDB#676]
SQL Server TPROC-C Driver Options screen needs scroll bar so i can configure all options
![2024-02-27 10_32_28-](https://github.com/TPC-Council/HammerDB/assets/161515585/1be9f673-86c2-4857-a942-08a7b7a7aa02)

Version 4.10

i can't see to the end of the configuration window to set/confirm options. I have no idea what is down there. Need a scroll bar on the side to help see everything.

![image](https://github.com/TPC-Council/HammerDB/assets/161515585/d593f620-e393-4565-a52a-05ca516f9fde)

**Comment by sm-shaw** [comment]
HammerDB uses SVG graphics to scale to adapt to the configured display settings on both Linux and Windows.

<img width="1128" alt="sqloptions" src="https://github.com/TPC-Council/HammerDB/assets/38044085/4219401d-7dee-4a22-b2ed-f5f7902b8612">

The documentation is available [here](https://www.hammerdb.com/docs4.3/ch01s10.html) and explains how to control this with the settings in config/generic.xml

The first thing you can do is change the screen resolution settings and HammerDB will pick these up. You can also tune the HammerDB scaling with the pixelsperpoint setting.

Alternatively you can go back to the older non-scaling graphics by setting scaling to "fixed" in generic.xml.

```
<theme>
<scaling>fixed</scaling>
<scaletheme>auto</scaletheme>
<pixelsperpoint>auto</pixelsperpoint>
</theme>
```

<img width="1128" alt="fixed" src="https://github.com/TPC-Council/HammerDB/assets/38044085/1efd4297-e252-4d2c-8227-2e950c3772b6">

Now having said that. Yes, if screen resolution settings are not optimal (and it is difficult to strike the balance for every possible display setting on Linux and Windows for all of the potential themes we have) then dialog boxes may appear too large as in your setting and we have been adding options all of the time making them longer.  This is particularly an issue for MySQL/MariaDB with all of the SSL options.  

Therefore the best option will be to move to notebook style tabbed options boxes with one tab for the connectivity options and another for the configuration settings. We have been aware of this and it has not reached the top of the run queue as yet.  However reviewing the v4.11 features draft has some SVG and theme related updates planned and it could be possible that change the dialogs to a tabbed notebook style can be done here.  An issue will be raised for the SVG updates once it has been reviewed.

**Comment by sm-shaw** [comment]
Example of  notebook style tabbed options boxes which reduces the size of the options dialog

<img width="276" alt="tab1" src="https://github.com/TPC-Council/HammerDB/assets/38044085/ba59dd1e-f0e5-425f-a619-a4e6f4ee589e">

<img width="276" alt="tab2" src="https://github.com/TPC-Council/HammerDB/assets/38044085/3c19f4f8-2379-4f4a-b53f-dc389b7b770d">
