### ISSUE TITLE
hammerdb docs ch03s07.html 7. Generating Time Profiles

### ISSUE THREAD

**Issue by KJlt77** [TPC-Council/HammerDB#74]
Unclear dimension of percentiles. Milliseconds?

**Comment by sm-shaw** [comment]
You are right - this is a documentation bug, the value was in the documentation but must have been removed at some point during a documentation update. The value is in microseconds.

**Comment by sm-shaw** [comment]
Issue is fixed in the documentation for version 3.3 https://github.com/TPC-Council/HammerDB/releases/tag/v3.3
