### ISSUE TITLE
SQL Server partitioned row store schema check failed tpch schema on table orders no indicies

### ISSUE THREAD

**Issue by sm-shaw** [TPC-Council/HammerDB#749]
**Guidance**
Bug reports are for when HammerDB is not behaving as expected.
Bug reports should not be submitted for help in understanding database performance related questions.
General questions on database performance or HammerDB usability should be submitted under Discussions.

**Describe the bug**
The schema check on SQL server with the partitioned option selected but not column store fails with the error:
`TPROC-H Schema check failed tpch schema on table orders no indicies`

**To Reproduce**
In SQL Server create a TPROC-H schema with partitioning selected and not columnstore and run the schema check. 

**Expected behavior**
The schema check should find indexes on the orders table and succeed. 

**Screenshots**
N/A

**HammerDB Version (please complete the following information):**
 - Version: Version 4.10 onwards
 - Build: both

**HammerDB Interface (please complete the following information):**
 - UI: Both

**Operating System (please complete the following information):**
 - Server OS: all
 - Client OS: all
 - 
**Database Server (please complete the following information):**
 - Database name: SQL Server
 - Database Release Version 

**Database Client (please complete the following information):**
 - Database client name:  ODBC Driver 18 for SQL Server

**Additional context**
Build needs modifying to add correct indexes

**Comment by JoshInnis** [comment]
In mssqlolap.tcl:
```
        set num_commands 28
        if { [expr {$partition_orders_and_lineitems != true } ] } {
            set num_commands 34
            set sql(29) "create clustered index o_orderdate_ind on orders(o_orderdate) with (fillfactor=95, sort_in_tempdb=on, maxdop=$maxdop)"
            set sql(30) "alter table dbo.orders add constraint orders_pk primary key (o_orderkey) with (fillfactor = 95, maxdop=$maxdop)"
            set sql(31) "alter table dbo.lineitem with nocheck add  constraint lineitem_order_fk foreign key(l_orderkey) references dbo.orders (o_orderkey)"
            set sql(32) "alter table dbo.lineitem with nocheck add  constraint lineitem_partsupp_fk foreign key(l_partkey,l_suppkey) references partsupp(ps_partkey, ps_suppkey)"
            set sql(33) "alter table dbo.lineitem check constraint lineitem_order_fk"
            set sql(34) "alter table dbo.lineitem check constraint lineitem_partsupp_fk"
        }
```

It seems like if we remove the if statement and merge these commands with the rest of the commands this issue would be solved.

**Comment by sm-shaw** [comment]
PR #750 does very similar, it moves some of the statements to the higher block, however the orders_pk primary key can't be just o_orderkey as it needs both partitioned columns. This also means we can't create lineitem_order_fk. The PR does the following. 

```
alter table dbo.orders add constraint orders_pk primary key (o_orderdate,o_orderkey) with (fillfactor = 95, maxdop=$maxdop)
create index o_orderkey_ind on orders(o_orderkey) with (fillfactor=95, sort_in_tempdb=on, maxdop=$maxdop)
```

As noted in the PR the o_orderkey_ind is so that the old sales refresh performs well. To test this select the refresh function with 1 VU and it will do new sales refresh - 1 query set - old sales refresh.
