### ISSUE TITLE
TPC-H cannot be executed for AWS RDS Oracle.

### ISSUE THREAD

**Issue by atsuizo** [TPC-Council/HammerDB#75]
The “SYSTEM” user is hard-coded without using the string specified by “system_user”. (oraolap.tcl: L795)

And also, “proc do_tpch” is not made to accept “system_user”.(oraolap.tcl: L740)

AWS RDS Oracle cannot use SYS and SYSTEM users as a restriction of DBaaS. Instead, you need to create a user with the highest available privileges with any name during the creation of a new instance and manage the database with that user.

I provisionally supported oraolap.tcl: L795 by directly rewriting it, but I expect it to be modified to work with the user specified by "system_user".

**Comment by sm-shaw** [comment]
Yes, you are correct many thanks for raising this. This was the same for the TPC-C workload and addressed for that. For TPC-H system user was added to the graphical interface but did not find its way into the build script. The variable is already there so should be straightforward to update the build script to add this parameter. Thank-you again.

**Comment by sm-shaw** [comment]
Issue is fixed in release 3.3.
