### ISSUE TITLE
Unable to specify PostgreSQL tablespace when building schema

### ISSUE THREAD

**Issue by remi9898** [TPC-Council/HammerDB#81]
Running HammerDB 3.3 on CentOS 7.7 kernel 3.10.0-1062.

The build schema options for PostgreSQL don't appear to allow specifying a tablespace.  For Oracle, the build schema options has line to enter tablespace name.  Not for PostgreSQL.

If I manually create the tpcc or tpch databases in my tablespace called hammerdb on /pgdata1/data, then HammerDB's build schema fails with error like "database tpch already exists".  

For now the workaround is to move template1 to my desired tablespace so that when HammerDB issues the create database statement the new database will inherit template1's tablespace setting.  Not best since I have to remember to change it back, and to change it each time I want to use a different tablespace.

Thanks.

**Comment by sm-shaw** [comment]
This is a valid feature request and straightforward to add.  Would you like to go ahead and try and add these changes yourself and submit a pull request to have them merged? This will be the quickest way for inclusion. If not it will be added to the list of feature requested and added when time permits.

**Comment by remi9898** [comment]
Thanks.  I'm not a good choice for modifying the code.

**Comment by sm-shaw** [comment]
Changes  added in Pull Request : PostgreSQL prepared statements for functions and tablespace option for schema builds #95

**Comment by sm-shaw** [comment]
Closed per pull request PostgreSQL prepared statements for functions and tablespace option for schema builds #95
