### ISSUE TITLE
Report Geomean for TPC-H Queries

### ISSUE THREAD

**Issue by emily-ygz** [TPC-Council/HammerDB#83]
The cloud analytic queries report the geomean for queries as noted in here by Oracle http://www.oracle.com/us/products/database/database-cloud-services-comparison-3227721.pdf (“The metric is the geometric mean of the query timing intervals from the power test.”) The TPC-H queries should also report the Geomean to prevent it being calculated manually.

**Comment by sm-shaw** [comment]
Good suggestion - the documentation has already been changed to recommend the geomean for comparing query results https://www.hammerdb.com/docs/ch10s02.html therefore it makes sense to report the geomean automatically at the end of a queryset as the cloud queries currently do. This will be added. Note as some of the open source solution cannot run all of the TPC-H queries it will continue to report the geomean for queries that were successfully run and it will be for the user to ensure that this is like for like with the same queries being compared.

**Comment by emily-ygz** [comment]
Thanks, good documentation!

**Comment by abondvt89** [comment]
Closing this issue since it was resolved via an accepted pull request.
